---

- name: Install Pulp Server
  package:
    name: "{{ item }}"
  with_items: "{{ pulp_server_pkgs }}"
  notify:
    - Restart Web service
    - Restart Pulp Workers service
    - Restart Pulp Celerybeat service
    - Restart Pulp Resource Manager service
  tags:
    - pulp_pkg

- name: Configure Pulp Server
  template:
    src: server.conf.j2
    dest: /etc/pulp/server.conf
  notify:
    - Restart Web service
    - Restart Pulp Workers service
    - Restart Pulp Celerybeat service
    - Restart Pulp Resource Manager service
  tags:
    - pulp_config

- name: Configure Pulp Server Plugins
  template:
    src: plugins.conf.j2
    dest:  /etc/pulp/server/plugins.conf.d/{{ item.key }}.json
    owner: "{{ pulp_web_service_user }}"
    group: "{{ pulp_web_service_group }}"
    mode: 0640
  notify:
    - Restart Web service
    - Restart Pulp Workers service
    - Restart Pulp Celerybeat service
    - Restart Pulp Resource Manager service
  with_dict: "{{ pulp_server_plugins_config }}"
  tags:
    - pulp_config

- name: Check if Pulp's DB was initialized
  stat:
    path: /var/lib/pulp/db_initialized.flag
  register: db_init
  tags:
    - pulp_config

- name: Initialize Pulp's DB
  shell: env su - {{ pulp_web_service_user }} -s /bin/bash -c pulp-manage-db && touch /var/lib/pulp/db_initialized.flag
  notify:
    - Restart Web service
    - Restart Pulp Workers service
    - Restart Pulp Celerybeat service
    - Restart Pulp Resource Manager service
  when: not db_init.stat.exists
  tags:
    - pulp_config

- name: Check if CA certificate exists
  stat:
    path: /etc/pki/pulp/ca.crt
  register: pulp_ca_file_check
  tags:
    - pulp_config

- name: Create CA certificate
  shell: pulp-gen-ca-certificate
  notify:
    - Restart Web service
    - Restart Pulp Workers service
    - Restart Pulp Celerybeat service
    - Restart Pulp Resource Manager service
  when: not pulp_ca_file_check.stat.exists
  tags:
    - pulp_config

- name: Create Pulp RSA keypair
  shell: pulp-gen-key-pair
  notify:
    - Restart Web Service
  creates: /etc/pki/pulp/rsa.key
  tags:
    - pulp_config

- name: Configure Pulp Workers
  template:
    src: pulp_workers.j2
    dest: /etc/default/pulp_workers
  notify:
    - Restart Pulp Workers service
  tags:
    - pulp_config

- name: Configure Pulp Repo Authentication
  template:
    src: repo_auth.conf.j2
    dest: /etc/pulp/repo_auth.conf
  notify:
    - Restart Pulp Workers service
    - Restart Pulp Celerybeat service
    - Restart Pulp Resource Manager service
  tags:
    - pulp_config

- name: Enable Web service
  service:
    name: "{{ pulp_web_service }}"
    enabled: yes
  tags:
    - pulp_service

- name: Run Web service
  service:
    name: "{{ pulp_web_service }}"
    state: started
  register: pulp_web_service_started
  tags:
    - pulp_service

- name: Enable Pulp Workers service
  service:
    name: pulp_workers
    enabled: yes
  tags:
    - pulp_service

- name: Run Pulp Workers service
  service:
    name: pulp_workers
    state: started
  register: pulp_workers_service_started
  tags:
    - pulp_service

- name: Enable Pulp Celerybeat service
  service:
    name: pulp_celerybeat
    enabled: yes
  when: pulp_run_celerybeat == true
  tags:
    - pulp_service

- name: Run Pulp Celerybeat service
  service:
    name: pulp_celerybeat
    state: started
  when: pulp_run_celerybeat == true
  register: pulp_celerybeat_service_started
  tags:
    - pulp_service

- name: Enable Pulp Resource Manager service
  service:
    name: pulp_resource_manager
    enabled: yes
  when: pulp_run_resource_manager == true
  tags:
    - pulp_service

- name: Run Pulp Resource Manager service
  service:
    name: pulp_resource_manager
    state: started
  when: pulp_run_resource_manager == true
  register: pulp_resource_manager_service_started
  tags:
    - pulp_service
